spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: alfrescobayer@gmail.com
    password: asdF1!333
    properties:
      mail:
        protocol: smtp
        tls: true
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
