
ecos:
  webapp:
    dataSources:
      main:
        url: jdbc:postgresql://localhost:5439/notifications
        username: notifications
        password:

spring:
  mail:
    host: localhost
    port: 25
    username:
    password:

server:
  port: 8013

ecos-notifications:
  error-notification:
    delay: 600000
  awaiting-dispatch:
    delay: 15000
  bulk-mail:
    sync-status-delay: 7000

notifications:
  default:
    locale: ru
    from: ecos.notifications@citeck.ru
