
ecos:
  webapp:
    dataSources:
      main:
        url: jdbc:postgresql://localhost:14523/ecos_notifications
        username: notifications
        password: notificationspassword

spring:
  mail:
    host: localhost
    port: 25
    username:
    password:
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

server:
  port: 8013

ecos-notifications:
  error-notification:
    delay: 600000
  awaiting-dispatch:
    delay: 15000
  bulk-mail:
    sync-status-delay: 7000

notifications:
  default:
    locale: ru
    from: ecos.notifications@citeck.ru
