
eureka:
    instance:
        hostname: host.docker.internal #doesn't work for linux
        ip-address: host.docker.internal #doesn't work for linux

alfresco:
    ribbon:
        listOfServers: localhost:8080
        NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList

eapps:
    ribbon:
        listOfServers: localhost:8089
        NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList

emodel:
    ribbon:
        listOfServers: localhost:8094
        NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList

