
ecos:
  webapp:
    dataSources:
      main:
        url: jdbc:postgresql://localhost:14523/ecos_notifications
        username: notifications
        password: notificationspassword
      main-xa-aware:
        url: ${ecos.webapp.dataSources.main.url}
        username: ${ecos.webapp.dataSources.main.username}
        password: ${ecos.webapp.dataSources.main.password}
        xa: true
  x509:
    keys:
      application:
        location: classpath:ecos/x509/keys/application.key

management:
  health:
    mail:
      enabled: false

spring:
  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

server:
  port: 8013

ecos-notifications:
  error-notification:
    delay: 600000
  awaiting-dispatch:
    delay: 15000
  bulk-mail:
    sync-status-delay: 7000
  startup-notification:
    enabled: true
    body: Microservice ecos-notifications successfully started and ready for operation. This is a test message – no reply is needed.
    title: Microservice ecos-notifications successfully started and ready for operation
    recipient: test@test.ru

notifications:
  default:
    locale: ru
