
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notifications
    username: notifications
    password:

ecos-notifications:
  firebase:
    credential-class-path: /credentials/citeck-ecos-firebase-adminsdk.json
    data-base-url: https://citeck-ecos-integration.firebaseio.com
