alfresco:
  ribbon:
    listOfServers: localhost:8080
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList

eapps:
  ribbon:
    listOfServers: localhost:8089
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
  watcher:
    artifacts:
      enabled: true
      locations: './src/main/resources/eapps/artifacts'

emodel:
  ribbon:
    listOfServers: localhost:8094
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList

ecos:
  zookeeper:
    host: localhost
    port: 2181
