package ru.citeck.ecos.notifications.domain.notification

const val NOTIFICATION_DATA = "_data"
const val NOTIFICATION_ATTACHMENTS = "_attachments"
const val NOTIFICATION_MODEL = "model"
const val NOTIFICATION_IGNORE_TEMPLATE = "ignoreTemplate"

const val NOTIFICATION_SYS_META_ATT = "_notification"
const val NOTIFICATION_SYS_META_TITLE_ATT = "title"
const val NOTIFICATION_SYS_META_FROM_ATT = "from"
const val NOTIFICATION_SYS_META_TO_ATT = "to"
const val NOTIFICATION_SYS_META_CC_ATT = "cc"
const val NOTIFICATION_SYS_META_BCC_ATT = "bcc"

const val NOTIFICATION_ATTACHMENT_META = "meta"
const val NOTIFICATION_ATTACHMENTS_PREVIEW_INFO = "previewInfo"
const val NOTIFICATION_ATTACHMENT_BYTES = "bytes"

const val NOTIFICATION_ATTACHMENT_ORIGINAL_NAME = "originalName"
const val NOTIFICATION_ATTACHMENT_NAME = "name"

const val NOTIFICATION_ATTACHMENT_ORIGINAL_EXT = "originalExt"
const val NOTIFICATION_ATTACHMENT_EXT = "ext"

const val NOTIFICATION_ATTACHMENT_MIMETYPE_LOWER = "mimetype"
const val NOTIFICATION_ATTACHMENT_MIMETYPE = "mimeType"

val NOTIFICATION_ATTACHMENT_MIMETYPE_ATTS = listOf(
    NOTIFICATION_ATTACHMENT_MIMETYPE,
    NOTIFICATION_ATTACHMENT_MIMETYPE_LOWER
)

val NOTIFICATION_ATTACHMENT_NAME_ATTS = listOf(
    NOTIFICATION_ATTACHMENT_NAME,
    NOTIFICATION_ATTACHMENT_ORIGINAL_NAME
)

val NOTIFICATION_ATTACHMENT_EXT_ATTS = listOf(
    NOTIFICATION_ATTACHMENT_EXT,
    NOTIFICATION_ATTACHMENT_ORIGINAL_EXT
)
